### ISSUE TITLE
Update package.json for Grunt 1.0.0

### ISSUE THREAD

**Issue by rmbl** [lesshint/grunt-lesshint#11]
The package.json file should be updated to also allow grunt 1.0.0 and later. It's already working with it, just throws a warning everytime I run ```npm install```

**Comment by kokarn** [comment]
Agreed. I'll have a look if you don't feel like publishing a PR :)

**Comment by kokarn** [comment]
Sorry it took so long. Fixed now with https://github.com/lesshint/grunt-lesshint/commit/a8e8e5638caca13f94534ac6e5d74a999496a319
