### ISSUE TITLE
Migration to lesshint 4.6.4

### ISSUE THREAD

**Issue by nighthavvk** [lesshint/grunt-lesshint#18]
Is there any chance to have `grunt-lesshint` migrated to latest version of `lesshint` (4.6.4) in nearest future?

**Comment by kokarn** [comment]
Yeah sure. That's probably something we should look into...

**Comment by kokarn** [comment]
This now fixed since https://github.com/lesshint/grunt-lesshint/commit/0fdcc64f418590706bc15c10fca1ac328bf3fc4e
Please install grunt-lesshint@2 to get the right version.

**Comment by maksymcharuk** [comment]
Great. Thank you!
