### ISSUE TITLE
Update lesshint to the last version

### ISSUE THREAD

**Issue by ethyde** [lesshint/grunt-lesshint#4]
Currently used version does not include decimalZero linter by example.

**Comment by kokarn** [comment]
I'll look into that. We're currently trying to push a 1.0 version tracked here https://github.com/lesshint/lesshint/issues/67 but i'll update this package as well.

**Comment by kokarn** [comment]
This is fixed with the addition of lesshint 1.0.
https://github.com/lesshint/grunt-lesshint/commit/d216f48e3841603e28be594e24d0899482d8a00c
