### ISSUE TITLE
Less Mixins cause error.

### ISSUE THREAD

**Issue by ethyde** [lesshint/grunt-lesshint#5]
Hi,

Since the last update, mixins generated the following error : 
```
λ grunt lesshint
Running "lesshint:target" (lesshint) task
Fatal error: Cannot read property 'content' of null
```
Even if they if are not used,

sorry for my bad english.

**Comment by kokarn** [comment]
Hmm, yeah we've noticed that in lesshint and are working on a fix. I think it's this issue https://github.com/lesshint/lesshint/issues/82

**Comment by kokarn** [comment]
Could you paste the less you use so we can test it?

**Comment by ethyde** [comment]
Sure : 
```
.box-sizing (@type: border-box) {
    -webkit-box-sizing: @type;
    -moz-box-sizing:    @type;
    box-sizing:         @type;
}

* {
    .box-sizing();
}
```

**Comment by kokarn** [comment]
Thank you so much! It's reported upsteam and we're working on it :)

**Comment by kokarn** [comment]
This should be fixed with lesshint >= 2
