### ISSUE TITLE
Add severity to task output

### ISSUE THREAD

**Issue by jwilsson** [lesshint/grunt-lesshint#7]
Since we added severity overrides support in `lesshint`, we probably want to make sure this is shown in the task output (ref: https://github.com/lesshint/lesshint/blob/062950f5df9c29df22af91e6fc9c023ac293b584/lib/reporters/stylish.js)

**Comment by mmckenziedev** [comment]
👍

**Comment by mmckenziedev** [comment]
At the moment, the task will be reported as failing even though the report only contains warnings. Can this be adjusted so that the task will also take the severity into account report a different result if only warnings have occurred?

**Comment by kokarn** [comment]
Yeah, that should be possible without too much work. 
Just add an option to "fail on warning" and some better logic here: https://github.com/lesshint/grunt-lesshint/blob/master/tasks/lesshint.js#L82-L96

Do you have the time to create a PR?

**Comment by mmckenziedev** [comment]
@kokarn I can do it, I'm just wondering how we want to implement this. For instance, the way I use eslint is that everything is a warning by default, and I have to explicitly set something to an error in order for the task to fail.

I made a branch here https://github.com/lesshint/grunt-lesshint/compare/master...mmckenziedev:add-warnings-to-ouput

The output would be something like:

```
3 warnings and 2 errors in 3 files and 114 clean files.
```
If the count of errors is zero, then the task will succeed.

**Comment by kokarn** [comment]
This looks great!

The only thing I would like is an option that enables this behavior. 
That way we're backwards compatible as well 🍰

**Comment by mmckenziedev** [comment]
I've added an option so that the new behavior will only be enabled if the user explicitly turns it on. I've also updated the documentation and wrote two tests to verify that the new functionality works as expected.

https://github.com/lesshint/grunt-lesshint/pull/15

**Comment by kokarn** [comment]
Thanks so much! Looks very good. Pushing a new version in a sec (sorry for the long wait)
